---
name: Build artifacts
on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            binary: digipy.exe
          - os: ubuntu-latest
            binary: digipy

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install -r dev.txt
      - run: make
      - run: ./dist/${{ matrix.binary }} version
      - run: tar czf ./dist/digipy-${{ matrix.os }}.tar.gz dist/${{ matrix.binary }}

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/digipy-${{ matrix.os }}.tar.gz
          asset_name: digipy-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
