---
name: Build artifacts
on:
  push:
    tags:
      - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - run: pip install -r dev.txt
      - run: make
      - run: ./dist/digipy version
      - run: tar czf ./dist/digipy-${{ matrix.os }}.tar.gz dist/digipy --remove-files

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/digipy-${{ matrix.os }}.tar.gz
          asset_name: digipy-${{ matrix.os }}.tar.gz
          tag: ${{ github.ref }}
